Vagrant.configure("2") do |config|

 # creating a virtual machine ubuntu
 config.vm.box = "ubuntu/xenial64"
 # create private network with the following ip
 config.vm.network "private_network", ip: "192.168.10.100"
 # Synced app folder
 config.vm.synced_folder ".", "/home/vagrant/app"
 # "." means from my current location where this vagrant file is copy everything and paste it in the VM on the home location vagrant create a folder called app and paste everything
 # Provisioning
 config.vm.provision "shell", path:"environment/provision.sh" 
 

end
